services:
  # Service web principal
  - type: web
    name: gestion-stock
    env: php
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader --ignore-platform-reqs
      php artisan config:clear
      php artisan cache:clear
      php artisan view:clear
      php artisan migrate --force
      php artisan db:seed --force
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_KEY
        generateValue: true
      - key: APP_URL
        value: https://gestion-stock-ol7b.onrender.com
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: 127.0.0.1
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: gestion_stock
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: CACHE_DRIVER
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: QUEUE_CONNECTION
        value: sync

  # Service de base de donn√©es MySQL
  - type: pserv
    name: mysql-db
    env: mysql
    plan: free
    healthCheckPath: /health
    envVars:
      - key: MYSQL_DATABASE
        value: gestion_stock
      - key: MYSQL_USER
        value: root
      - key: MYSQL_PASSWORD
        value: ""
